name: Build and Deploy

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-1
  S3BUCKET: myvpc123-deploymentbucket

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - run: ./zip_folder.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: webapp.pkr.hcl

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: webapp.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: webapp.pkr.hcl
        env:
          PACKER_LOG: 1

  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - run: ./zip_folder.sh
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{secrets.PROD_AWS_ACCESS_ID}}
          aws-secret-access-key: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      - name: Upload Artifact to s3
        run: aws s3 cp webapp.zip s3://${{ env.S3BUCKET }}/

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@@v1-node16
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment \
          --application-name CodeDeployAppNameWithASG \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name CodeDeployGroupName \
          --description "CSYE6255 - CodeDeploy" \
          --s3-location bucket=${{secrets.S3BUCKET}},key=webapp.zip,bundleType=zip \
          --region ${{secrets.AWS_REGION}} \
          --output json)
